FROM python:3.11-slim

# Define diretório de trabalho
WORKDIR /paggo/source-api

# Copia os arquivos de requirements
COPY source-api/requirements.txt .

# Instala os pacotes Python
RUN pip install --no-cache-dir -r requirements.txt

# Copia o restante do código do projeto
COPY source-api/ .

# Expor a porta (por padrão FastAPI usa 8000)
EXPOSE 8000

# Comando padrão para rodar a API em modo dev

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
